# Generated by Django 2.1 on 2021-05-10 21:20

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_of_manufacture', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('image', s3direct.fields.S3DirectField(blank=True)),
                ('video', s3direct.fields.S3DirectField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
