# Generated by Django 3.1.1 on 2021-05-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_media_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.FileField(null=True, upload_to='videos/youtube/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='full_text',
            field=models.FileField(null=True, upload_to='texts/'),
        ),
    ]
