# Generated by Django 3.2.3 on 2021-05-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_auto_20210523_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YoutubeData',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='subscribers',
        ),
    ]
