# Generated by Django 3.2.2 on 2021-05-10 23:41

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20210510_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
