# Generated by Django 3.1.1 on 2021-05-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_auto_20210512_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('video', 'video'), ('audio', 'audio')], default='video', max_length=5),
        ),
    ]
